[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:python3_host_prog = '/opt/local/bin/python'
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
   inoremap <expr><tab> pumvisible() ? "\<C-n>" :
         \ neosnippet#expandable_or_jumpable() ?
         \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
hook_source = '''
  let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '-r @line @pdf @tex'
  let g:vimtex_view_general_options_latexmk = '-r 1'
'''
on_ft = ['tex']

[[plugins]]
repo = 'cohama/lexima.vim'
hook_post_source = '''
  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': ['tex', 'plaintex']})
  call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': ['tex', 'plaintex']})
  call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': ['tex', 'plaintex']})
  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'tex'})
  call lexima#add_rule({'char': '$', 'at': '%#$', 'leave': 1, 'filetype': 'tex'})
  call lexima#add_rule({'char': '', 'at': '$%#$', 'delete': 1, 'filetype': 'tex'})
  " 後ろの補完を抜ける
  call lexima#add_rule({'char': '<TAB>', 'at': '\%#)', 'leave': 1})
  call lexima#add_rule({'char': '<TAB>', 'at': '\%#"', 'leave': 1})
  call lexima#add_rule({'char': '<TAB>', 'at': "\%#'", 'leave': 1})
  call lexima#add_rule({'char': '<TAB>', 'at': '\%#]', 'leave': 1})
  call lexima#add_rule({'char': '<TAB>', 'at': '\%#}', 'leave': 1})
  call lexima#add_rule({'char': '<TAB>', 'at': '\%#\$', 'leave': 1, 'filetype': 'tex'})
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target
  " force quitting conceal
  " let g:tex_conceal=''
  " conceal (NOT recommended!)
  "   if has('conceal')
  "     set conceallevel=2 concealcursor=niv
  "   endif
  let g:neosnippet#snippets_directory='/Users/takuya/.vim/mysnippets'
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
